Update fr-FR.js
kyranet/Skyra-i18n pull request #10
Opened 2018-03-26 19:07 UTC by RoblochOne

Delete lign 86 ? How much and how many it's the same thing in french. I stoped to the lign 250.
Æ.

2018-03-27 09:23 UTC, Pandraghon commented on languages/fr-FR.js
> +	WHAT: ['Un avion.', 'Quoi? Demande encore.', 'Un cadeau.', 'Rien.', 'Une cloche.', 'Je ne sais pas, peut-être quelque chose.'],
If a ring === :ring: , then it should be "Une bague"

2018-03-27 09:23 UTC, Pandraghon commented on languages/fr-FR.js
> +	WHY: ['Peut-être génétique.', 'Parce que quelqu\'un l\'a décidé comme ça.', 'Pour la gloire de Satan, évidemment !', 'Je ne sais pas, peut-être le destin.', 'Parce que je l'ai dit.', 'Je n'en ai auc
`côté`

2018-03-27 09:23 UTC, Pandraghon commented on languages/fr-FR.js
> +				extendedHelp: `ette commande utilise MyAnimeList pour montrer les données du manga que vous demandez. Dans un futur proche, cette commande',
`Cette`

2018-03-27 09:23 UTC, Pandraghon commented on languages/fr-FR.js
> +				qui ne peut pas être mentionné (pour éviter ceux qui spamment les rôles), et une fois que vous avez utilisé cette commande,
`et à chaque fois que vous utiliserez cette commande` fits better, IMO

2018-03-27 11:11 UTC, RoblochOne commented on languages/fr-FR.js
> +				extendedHelp: `ette commande utilise MyAnimeList pour montrer les données du manga que vous demandez. Dans un futur proche, cette commande',
Merci d'avoir trouvé cette faute de frappe

2018-03-27 11:12 UTC, RoblochOne commented on languages/fr-FR.js
> +	WHY: ['Peut-être génétique.', 'Parce que quelqu\'un l\'a décidé comme ça.', 'Pour la gloire de Satan, évidemment !', 'Je ne sais pas, peut-être le destin.', 'Parce que je l'ai dit.', 'Je n'en ai auc
Avec la nouvelle réforme de l'orthographe, je ne suis pas sur que le ^ soit encore obligatoire mais je vais le modifier

2018-03-27 11:14 UTC, RoblochOne commented on languages/fr-FR.js
> +				qui ne peut pas être mentionné (pour éviter ceux qui spamment les rôles), et une fois que vous avez utilisé cette commande,
Merci de cette remarque

2018-03-27 11:15 UTC, RoblochOne commented on languages/fr-FR.js
> +	WHAT: ['Un avion.', 'Quoi? Demande encore.', 'Un cadeau.', 'Rien.', 'Une cloche.', 'Je ne sais pas, peut-être quelque chose.'],
Ca a plus de sens c'est vrai.. x)

2018-03-27 11:36 UTC, RoblochOne commented
I corrected the errors who has been detected by Pandraghon and I continued the translation
Æ.

2018-03-27 12:34 UTC, Pandraghon commented on languages/fr-FR.js
> +					administrateurs du serveur. Quand un modérateur ou un administrateur utilise la commande **annoncement**, vous
Sauf si la commande est traduite (dans ce cas, ne pas tenir compte de ma remarque), ne vaut-il pas mieux utiliser son nom tel quel ? ~~annoncement~~ announcement

2018-08-13 08:18 UTC, Pandraghon requested changes

2018-08-13 08:18 UTC, Pandraghon commented on languages/fr-FR.js
> +					responsable de se qui se passe après.`,
`de ce qui se passe après`

2018-08-13 08:18 UTC, Pandraghon commented on languages/fr-FR.js
> +				extendedHelp: `Vous savez que les chats sont très curieux, n'est-ce pas? Ils ont certainnement beaucoup de caractéristiques amusantes et bizarres.
Par soucis d'homogénéité, je mettrais une espace (typographique) avant le `?`.
Cette espace est facultative, mais les autres phrases en ont une.

2019-08-29 11:10 UTC, closed without merging